/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BorrowedBooKResponse } from './borrowed-book-response';
export interface PageResponseBorrowedBooKResponse {
  content?: Array<BorrowedBooKResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
